// <auto-generated />
using Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Data.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MenuCardId");

                    b.Property<int>("Price");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("MenuCardId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Data.Domain.Entities.MenuCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AllergyInfo");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("MenuCards");
                });

            modelBuilder.Entity("Data.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Data.Domain.Entities.MenuCard")
                        .WithMany("Menus")
                        .HasForeignKey("MenuCardId");
                });
#pragma warning restore 612, 618
        }
    }
}
